# Generated by Django 4.0.5 on 2023-01-12 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='lokacija',
            field=models.CharField(default='Sarajevo', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='opis',
            field=models.CharField(default='Opis restorana', max_length=300),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='vlasnik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
