# Generated by Django 4.0.5 on 2023-01-27 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_restaurants_lokacija_restaurants_opis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='lokacija',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='opis',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='vlasnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rezervacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br_osoba', models.IntegerField()),
                ('datum', models.CharField(max_length=50)),
                ('vrijeme', models.CharField(max_length=50)),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.restaurants')),
            ],
        ),
    ]
